on: [push, pull_request]
name: Test
jobs:
  build:
    strategy:
      matrix:
        go-os: [linux, darwin, windows]
        go-arch: [amd64]
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -o hds-migrator-${{ matrix.go-os }}-${{ matrix.go-arch }} 
      env:
        GOOS: ${{ matrix.go-os }}
        GOARCH: ${{ matrix.go-arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: hds-migrator-${{ matrix.go-os }}-${{ matrix.go-arch }}
        # Directory containing files to upload
        path: hds-migrator-${{ matrix.go-os }}-${{ matrix.go-arch }}
    - name: Release
      if: github.ref == 'ref/head/v*'
      uses: softprops/action-gh-release@v0.1.5
      with:
        files: hds-migrator-${{ matrix.go-os }}-${{ matrix.go-arch }}
