name: Go-Release
on:
  push:
    tags:
      - '*'
jobs:
  release-all-platforms: 
    strategy:
      matrix:
        goarch: [amd64]
        goos: [linux, darwin,windows ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: release
      uses: goreleaser/goreleaser-action@v1.3.1
      with:
        go-version: 1.14.x
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
