on: [push, pull_request]
name: Test
jobs:
  test:

    strategy:
      matrix:
        go-os: [linux, darwin, windows]
        go-arch: [amd64]
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -o hds-migrator-${{ matrix.go-os }}-${{ matrix.go-arch }} 
      env:
        GOOS: ${{ matrix.go-os }}
        GOARCH: ${{ matrix.go-arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: main-${{ matrix.go-os }}-${{ matrix.go-arch }}
        # Directory containing files to upload
        path: main-${{ matrix.go-os }}-${{ matrix.go-arch }}
